"""Import each transform submodule so its register() runs at import time."""

from yt_uniquifier.core.transforms import (
    audio_compand,
    audio_eq,
    audio_haas,
    audio_loudnorm,
    audio_noise_overlay,
    audio_pitch,
    audio_resample,
    audio_reverb,
    audio_spectral_smear,
    video_blend,
    video_color,
    video_geom,
    video_noise,
    video_speed,
    video_subpixel_sharpen,
    video_temporal_jitter,
    video_tonemap,
)
from yt_uniquifier.core.transforms.base import (
    FilterChain,
    LabelAllocator,
    TransformSpec,
    all_ids,
    get,
    register,
)

__all__ = [
    "FilterChain",
    "LabelAllocator",
    "TransformSpec",
    "all_ids",
    "audio_compand",
    "audio_eq",
    "audio_haas",
    "audio_loudnorm",
    "audio_noise_overlay",
    "audio_pitch",
    "audio_resample",
    "audio_reverb",
    "audio_spectral_smear",
    "get",
    "register",
    "video_blend",
    "video_color",
    "video_geom",
    "video_noise",
    "video_speed",
    "video_subpixel_sharpen",
    "video_temporal_jitter",
    "video_tonemap",
]
